services:
  laravel:
    container_name: laravel
    image: donovanbroquin/iut-laravel:latest
    networks:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/app
  
  redis:
    container_name: redis
    image: redis:7.4.0
    networks: 
      - laravel
    volumes:
      - ./.docker/stores/redis:/data

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.20.0
    networks:
      - laravel
    ports:
      - 8025:8025

networks:
  laravel:
    driver: bridge