---
- name: Set directory path variable
  ansible.builtin.set_fact:
    directory: "/home/{{ ansible_user }}/apps"

- name: Create directory for the compose file
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: '0755'

- name: Copy compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ directory }}/compose.yml"
    mode: '0644'

- name: Copy .env file
  ansible.builtin.copy:
    src: .env
    dest: "{{ directory }}/.env"
    mode: '0644'

- name: Pull images
  ansible.builtin.command: docker compose pull
  args:
    chdir: "{{ directory }}"

- name: Down services
  ansible.builtin.command: docker compose down --remove-orphans
  args:
    chdir: "{{ directory }}"

- name: Up services
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ directory }}"
