services:
  traefik:
    image: traefik:v3.1.2
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.forwardedHeaders.insecure=true
      - --api.insecure=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    networks:
      - iut
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/dynamic/traefik.yml
      - letsencrypt:/acme
    labels:
      - traefik.http.routers.api.rule=Host(`iut.${DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$sQXd7k0o$$8LKmP.xsS5mX2DlJNkjnn.

networks:
  iut:
    driver: bridge
    name: iut

volumes:
  letsencrypt:
    name: letsencrypt
